/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module adder(i_clk, i_rst_n, aa, bb, c);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  input [63:0] aa;
  input [63:0] bb;
  output [63:0] c;
  reg [63:0] c_r;
  wire [63:0] c_w;
  input i_clk;
  input i_rst_n;
  reg [32:0] tempa_r;
  wire [32:0] tempa_w;
  reg [31:0] tempb_r;
  wire [31:0] tempb_w;
  assign _000_ = aa[31] & bb[31];
  assign _001_ = ~(aa[31] ^ bb[31]);
  assign _002_ = aa[30] & bb[30];
  assign _003_ = _002_ & ~(_001_);
  assign _004_ = _003_ | _000_;
  assign _005_ = ~(aa[30] ^ bb[30]);
  assign _006_ = ~(_005_ | _001_);
  assign _007_ = aa[29] & bb[29];
  assign _008_ = ~(aa[29] ^ bb[29]);
  assign _009_ = aa[28] & bb[28];
  assign _010_ = _009_ & ~(_008_);
  assign _011_ = _010_ | _007_;
  assign _012_ = ~((_011_ & _006_) | _004_);
  assign _013_ = ~(aa[28] ^ bb[28]);
  assign _014_ = ~(_013_ | _008_);
  assign _015_ = ~(_014_ & _006_);
  assign _016_ = aa[27] & bb[27];
  assign _017_ = ~(aa[27] ^ bb[27]);
  assign _018_ = aa[26] & bb[26];
  assign _019_ = _018_ & ~(_017_);
  assign _020_ = _019_ | _016_;
  assign _021_ = ~(aa[26] ^ bb[26]);
  assign _022_ = ~(_021_ | _017_);
  assign _023_ = ~(aa[25] ^ bb[25]);
  assign _024_ = aa[24] & bb[24];
  assign _025_ = _024_ & ~(_023_);
  assign _026_ = ~((aa[25] & bb[25]) | _025_);
  assign _027_ = _022_ & ~(_026_);
  assign _028_ = ~(_027_ | _020_);
  assign _029_ = ~((_028_ | _015_) & _012_);
  assign _030_ = ~(aa[24] ^ bb[24]);
  assign _031_ = _030_ | _023_;
  assign _032_ = _022_ & ~(_031_);
  assign _033_ = _032_ & ~(_015_);
  assign _034_ = aa[23] & bb[23];
  assign _035_ = aa[23] ^ bb[23];
  assign _036_ = ~(aa[22] & bb[22]);
  assign _037_ = _035_ & ~(_036_);
  assign _038_ = _037_ | _034_;
  assign _039_ = ~(aa[22] ^ bb[22]);
  assign _040_ = _035_ & ~(_039_);
  assign _041_ = aa[21] ^ bb[21];
  assign _042_ = ~(aa[20] & bb[20]);
  assign _043_ = _041_ & ~(_042_);
  assign _044_ = ~((aa[21] & bb[21]) | _043_);
  assign _045_ = _040_ & ~(_044_);
  assign _046_ = _045_ | _038_;
  assign _047_ = ~(aa[20] ^ bb[20]);
  assign _048_ = _047_ | ~(_041_);
  assign _049_ = _040_ & ~(_048_);
  assign _050_ = aa[19] & bb[19];
  assign _051_ = aa[19] ^ bb[19];
  assign _052_ = ~(aa[18] & bb[18]);
  assign _053_ = _051_ & ~(_052_);
  assign _054_ = _053_ | _050_;
  assign _055_ = ~(aa[18] ^ bb[18]);
  assign _056_ = _051_ & ~(_055_);
  assign _057_ = aa[17] ^ bb[17];
  assign _058_ = ~(aa[16] & bb[16]);
  assign _059_ = _057_ & ~(_058_);
  assign _060_ = ~((aa[17] & bb[17]) | _059_);
  assign _061_ = _056_ & ~(_060_);
  assign _062_ = ~(_061_ | _054_);
  assign _063_ = _049_ & ~(_062_);
  assign _064_ = _063_ | _046_;
  assign _065_ = ~((_064_ & _033_) | _029_);
  assign _066_ = ~(aa[16] ^ bb[16]);
  assign _067_ = _066_ | ~(_057_);
  assign _068_ = _056_ & ~(_067_);
  assign _069_ = _068_ & _049_;
  assign _070_ = ~(_069_ & _033_);
  assign _071_ = aa[15] & bb[15];
  assign _072_ = aa[15] ^ bb[15];
  assign _073_ = ~(aa[14] & bb[14]);
  assign _074_ = _072_ & ~(_073_);
  assign _075_ = _074_ | _071_;
  assign _076_ = ~(aa[14] ^ bb[14]);
  assign _077_ = _072_ & ~(_076_);
  assign _078_ = ~(aa[13] & bb[13]);
  assign _079_ = ~(aa[13] ^ bb[13]);
  assign _080_ = ~(aa[12] & bb[12]);
  assign _081_ = ~((_080_ | _079_) & _078_);
  assign _082_ = ~((_081_ & _077_) | _075_);
  assign _083_ = ~(aa[12] ^ bb[12]);
  assign _084_ = _083_ | _079_;
  assign _085_ = _084_ | ~(_077_);
  assign _086_ = aa[11] & bb[11];
  assign _087_ = aa[11] ^ bb[11];
  assign _088_ = ~(aa[10] & bb[10]);
  assign _089_ = _087_ & ~(_088_);
  assign _090_ = _089_ | _086_;
  assign _091_ = ~(aa[10] ^ bb[10]);
  assign _092_ = _087_ & ~(_091_);
  assign _093_ = aa[9] & bb[9];
  assign _094_ = aa[9] ^ bb[9];
  assign _095_ = ~(aa[8] & bb[8]);
  assign _096_ = _094_ & ~(_095_);
  assign _097_ = _096_ | _093_;
  assign _098_ = ~((_097_ & _092_) | _090_);
  assign _099_ = ~((_098_ | _085_) & _082_);
  assign _100_ = ~(aa[8] ^ bb[8]);
  assign _101_ = _100_ | ~(_094_);
  assign _102_ = _101_ | ~(_092_);
  assign _103_ = ~(_102_ | _085_);
  assign _104_ = aa[7] & bb[7];
  assign _105_ = aa[7] ^ bb[7];
  assign _106_ = ~(aa[6] & bb[6]);
  assign _107_ = _105_ & ~(_106_);
  assign _108_ = _107_ | _104_;
  assign _109_ = ~(aa[6] ^ bb[6]);
  assign _110_ = _105_ & ~(_109_);
  assign _111_ = ~(aa[5] & bb[5]);
  assign _112_ = ~(aa[5] ^ bb[5]);
  assign _113_ = ~(aa[4] & bb[4]);
  assign _114_ = ~((_113_ | _112_) & _111_);
  assign _115_ = ~((_114_ & _110_) | _108_);
  assign _116_ = ~(aa[4] ^ bb[4]);
  assign _117_ = _116_ | _112_;
  assign _118_ = _117_ | ~(_110_);
  assign _119_ = aa[3] & bb[3];
  assign _120_ = aa[3] ^ bb[3];
  assign _121_ = ~(aa[2] & bb[2]);
  assign _122_ = _120_ & ~(_121_);
  assign _123_ = _122_ | _119_;
  assign _124_ = ~(aa[2] ^ bb[2]);
  assign _125_ = _120_ & ~(_124_);
  assign _126_ = aa[1] & bb[1];
  assign _127_ = aa[1] ^ bb[1];
  assign _128_ = ~(aa[0] & bb[0]);
  assign _129_ = _127_ & ~(_128_);
  assign _130_ = _129_ | _126_;
  assign _131_ = ~((_130_ & _125_) | _123_);
  assign _132_ = ~((_131_ | _118_) & _115_);
  assign _133_ = ~((_132_ & _103_) | _099_);
  assign tempa_w[32] = ~((_133_ | _070_) & _065_);
  assign _134_ = bb[32] ^ aa[32];
  assign tempb_w[0] = _134_ ^ tempa_r[32];
  assign _135_ = ~(bb[33] ^ aa[33]);
  assign _136_ = bb[32] & aa[32];
  assign _137_ = ~((_134_ & tempa_r[32]) | _136_);
  assign tempb_w[1] = _137_ ^ _135_;
  assign _138_ = bb[34] ^ aa[34];
  assign _139_ = ~(bb[33] & aa[33]);
  assign _140_ = ~((_137_ | _135_) & _139_);
  assign tempb_w[2] = _140_ ^ _138_;
  assign _141_ = ~(bb[35] ^ aa[35]);
  assign _142_ = ~(bb[34] & aa[34]);
  assign _143_ = ~_142_;
  assign _144_ = ~((_140_ & _138_) | _143_);
  assign tempb_w[3] = _144_ ^ _141_;
  assign _145_ = ~(bb[36] ^ aa[36]);
  assign _146_ = ~(bb[35] & aa[35]);
  assign _147_ = ~((_142_ | _141_) & _146_);
  assign _148_ = _138_ & ~(_141_);
  assign _149_ = ~((_148_ & _140_) | _147_);
  assign tempb_w[4] = _149_ ^ _145_;
  assign _150_ = bb[37] ^ aa[37];
  assign _151_ = ~(bb[36] & aa[36]);
  assign _152_ = ~((_149_ | _145_) & _151_);
  assign tempb_w[5] = _152_ ^ _150_;
  assign _153_ = bb[38] ^ aa[38];
  assign _154_ = bb[37] & aa[37];
  assign _155_ = _150_ & ~(_151_);
  assign _156_ = _155_ | _154_;
  assign _157_ = ~_156_;
  assign _158_ = _145_ | ~(_150_);
  assign _159_ = ~((_158_ | _149_) & _157_);
  assign tempb_w[6] = _159_ ^ _153_;
  assign _160_ = ~(bb[39] ^ aa[39]);
  assign _161_ = ~(bb[38] & aa[38]);
  assign _162_ = ~_161_;
  assign _163_ = ~((_159_ & _153_) | _162_);
  assign tempb_w[7] = _163_ ^ _160_;
  assign _164_ = bb[40] ^ aa[40];
  assign _165_ = ~(bb[39] & aa[39]);
  assign _166_ = ~((_161_ | _160_) & _165_);
  assign _167_ = _153_ & ~(_160_);
  assign _168_ = ~((_167_ & _156_) | _166_);
  assign _169_ = _158_ | ~(_167_);
  assign _170_ = ~((_169_ | _149_) & _168_);
  assign tempb_w[8] = _170_ ^ _164_;
  assign _171_ = bb[41] ^ aa[41];
  assign _172_ = ~(bb[40] & aa[40]);
  assign _173_ = ~_172_;
  assign _174_ = ~((_170_ & _164_) | _173_);
  assign tempb_w[9] = ~(_174_ ^ _171_);
  assign _175_ = bb[42] ^ aa[42];
  assign _176_ = bb[41] & aa[41];
  assign _177_ = _171_ & ~(_172_);
  assign _178_ = _177_ | _176_;
  assign _179_ = ~(_171_ & _164_);
  assign _180_ = _170_ & ~(_179_);
  assign _181_ = _180_ | _178_;
  assign tempb_w[10] = _181_ ^ _175_;
  assign _182_ = ~(bb[43] ^ aa[43]);
  assign _183_ = ~(bb[42] & aa[42]);
  assign _184_ = ~_183_;
  assign _185_ = ~((_181_ & _175_) | _184_);
  assign tempb_w[11] = _185_ ^ _182_;
  assign _186_ = ~(bb[44] ^ aa[44]);
  assign _187_ = ~(bb[43] & aa[43]);
  assign _188_ = ~((_183_ | _182_) & _187_);
  assign _189_ = _175_ & ~(_182_);
  assign _190_ = ~((_189_ & _178_) | _188_);
  assign _191_ = ~_190_;
  assign _192_ = _189_ & ~(_179_);
  assign _193_ = ~((_192_ & _170_) | _191_);
  assign tempb_w[12] = _193_ ^ _186_;
  assign _194_ = bb[45] ^ aa[45];
  assign _195_ = ~(bb[44] & aa[44]);
  assign _196_ = ~((_193_ | _186_) & _195_);
  assign tempb_w[13] = _196_ ^ _194_;
  assign _197_ = bb[46] ^ aa[46];
  assign _198_ = bb[45] & aa[45];
  assign _199_ = _194_ & ~(_195_);
  assign _200_ = _199_ | _198_;
  assign _201_ = ~_200_;
  assign _202_ = _186_ | ~(_194_);
  assign _203_ = ~((_202_ | _193_) & _201_);
  assign tempb_w[14] = _203_ ^ _197_;
  assign _204_ = ~(bb[47] ^ aa[47]);
  assign _205_ = ~(bb[46] & aa[46]);
  assign _206_ = ~_205_;
  assign _207_ = ~((_203_ & _197_) | _206_);
  assign tempb_w[15] = _207_ ^ _204_;
  assign _208_ = ~(bb[48] ^ aa[48]);
  assign _209_ = ~(bb[47] & aa[47]);
  assign _210_ = ~((_205_ | _204_) & _209_);
  assign _211_ = _197_ & ~(_204_);
  assign _212_ = ~((_211_ & _200_) | _210_);
  assign _213_ = _202_ | ~(_211_);
  assign _214_ = ~((_213_ | _190_) & _212_);
  assign _215_ = _192_ & ~(_213_);
  assign _216_ = ~((_215_ & _170_) | _214_);
  assign tempb_w[16] = _216_ ^ _208_;
  assign _217_ = bb[49] ^ aa[49];
  assign _218_ = ~(bb[48] & aa[48]);
  assign _219_ = ~((_216_ | _208_) & _218_);
  assign tempb_w[17] = _219_ ^ _217_;
  assign _220_ = bb[50] ^ aa[50];
  assign _221_ = bb[49] & aa[49];
  assign _222_ = _217_ & ~(_218_);
  assign _223_ = _222_ | _221_;
  assign _224_ = ~_223_;
  assign _225_ = _208_ | ~(_217_);
  assign _226_ = ~((_225_ | _216_) & _224_);
  assign tempb_w[18] = _226_ ^ _220_;
  assign _227_ = bb[51] ^ aa[51];
  assign _228_ = ~(bb[50] & aa[50]);
  assign _229_ = ~_228_;
  assign _230_ = ~((_226_ & _220_) | _229_);
  assign tempb_w[19] = ~(_230_ ^ _227_);
  assign _231_ = bb[52] ^ aa[52];
  assign _232_ = bb[51] & aa[51];
  assign _233_ = _227_ & ~(_228_);
  assign _234_ = _233_ | _232_;
  assign _235_ = ~(_227_ & _220_);
  assign _236_ = _223_ & ~(_235_);
  assign _237_ = ~(_236_ | _234_);
  assign _238_ = _235_ | _225_;
  assign _239_ = ~((_238_ | _216_) & _237_);
  assign tempb_w[20] = _239_ ^ _231_;
  assign _240_ = bb[53] ^ aa[53];
  assign _241_ = ~(bb[52] & aa[52]);
  assign _242_ = ~_241_;
  assign _243_ = ~((_239_ & _231_) | _242_);
  assign tempb_w[21] = ~(_243_ ^ _240_);
  assign _244_ = bb[54] ^ aa[54];
  assign _245_ = bb[53] & aa[53];
  assign _246_ = _240_ & ~(_241_);
  assign _247_ = _246_ | _245_;
  assign _248_ = ~(_240_ & _231_);
  assign _249_ = _239_ & ~(_248_);
  assign _250_ = _249_ | _247_;
  assign tempb_w[22] = _250_ ^ _244_;
  assign _251_ = bb[55] ^ aa[55];
  assign _252_ = ~(bb[54] & aa[54]);
  assign _253_ = ~_252_;
  assign _254_ = ~((_250_ & _244_) | _253_);
  assign tempb_w[23] = ~(_254_ ^ _251_);
  assign _255_ = bb[56] ^ aa[56];
  assign _256_ = _236_ | _234_;
  assign _257_ = bb[55] & aa[55];
  assign _258_ = _251_ & ~(_252_);
  assign _259_ = _258_ | _257_;
  assign _260_ = ~(_251_ & _244_);
  assign _261_ = _247_ & ~(_260_);
  assign _262_ = _261_ | _259_;
  assign _263_ = ~(_260_ | _248_);
  assign _264_ = ~((_263_ & _256_) | _262_);
  assign _265_ = _238_ | ~(_263_);
  assign _266_ = ~((_265_ | _216_) & _264_);
  assign tempb_w[24] = _266_ ^ _255_;
  assign _267_ = ~(bb[57] ^ aa[57]);
  assign _268_ = bb[56] & aa[56];
  assign _269_ = ~((_266_ & _255_) | _268_);
  assign tempb_w[25] = _269_ ^ _267_;
  assign _270_ = ~(bb[58] ^ aa[58]);
  assign _271_ = ~_270_;
  assign _272_ = bb[57] & aa[57];
  assign _273_ = _268_ & ~(_267_);
  assign _274_ = ~(_273_ | _272_);
  assign _275_ = ~_274_;
  assign _276_ = _255_ & ~(_267_);
  assign _277_ = ~_276_;
  assign _278_ = _266_ & ~(_277_);
  assign _279_ = _278_ | _275_;
  assign tempb_w[26] = _279_ ^ _271_;
  assign _280_ = ~(bb[59] ^ aa[59]);
  assign _281_ = bb[58] & aa[58];
  assign _282_ = ~((_279_ & _271_) | _281_);
  assign tempb_w[27] = _282_ ^ _280_;
  assign _283_ = ~(bb[60] ^ aa[60]);
  assign _284_ = bb[59] & aa[59];
  assign _285_ = _281_ & ~(_280_);
  assign _286_ = ~(_285_ | _284_);
  assign _287_ = _280_ | _270_;
  assign _288_ = ~((_287_ | _274_) & _286_);
  assign _289_ = _276_ & ~(_287_);
  assign _290_ = ~((_289_ & _266_) | _288_);
  assign tempb_w[28] = _290_ ^ _283_;
  assign _291_ = ~(bb[61] ^ aa[61]);
  assign _292_ = bb[60] & aa[60];
  assign _293_ = ~_292_;
  assign _294_ = ~((_290_ | _283_) & _293_);
  assign tempb_w[29] = ~(_294_ ^ _291_);
  assign _295_ = ~(bb[62] ^ aa[62]);
  assign _296_ = ~_295_;
  assign _297_ = _292_ & ~(_291_);
  assign _298_ = ~((bb[61] & aa[61]) | _297_);
  assign _299_ = ~(_291_ | _283_);
  assign _300_ = ~_299_;
  assign _301_ = ~((_300_ | _290_) & _298_);
  assign tempb_w[30] = _301_ ^ _296_;
  assign _302_ = ~(bb[63] ^ aa[63]);
  assign _303_ = bb[62] & aa[62];
  assign _304_ = ~((_301_ & _296_) | _303_);
  assign tempb_w[31] = _304_ ^ _302_;
  assign tempa_w[1] = ~(_128_ ^ _127_);
  assign tempa_w[2] = ~(_130_ ^ _124_);
  assign _305_ = ~_130_;
  assign _306_ = ~((_305_ | _124_) & _121_);
  assign tempa_w[3] = _306_ ^ _120_;
  assign tempa_w[4] = _131_ ^ _116_;
  assign _307_ = ~((_131_ | _116_) & _113_);
  assign tempa_w[5] = ~(_307_ ^ _112_);
  assign _308_ = ~(_131_ | _117_);
  assign _309_ = _308_ | _114_;
  assign tempa_w[6] = ~(_309_ ^ _109_);
  assign _310_ = _309_ & ~(_109_);
  assign _311_ = _106_ & ~(_310_);
  assign tempa_w[7] = ~(_311_ ^ _105_);
  assign tempa_w[8] = ~(_132_ ^ _100_);
  assign _312_ = ~_132_;
  assign _313_ = ~((_312_ | _100_) & _095_);
  assign tempa_w[9] = _313_ ^ _094_;
  assign _314_ = _132_ & ~(_101_);
  assign _315_ = _314_ | _097_;
  assign tempa_w[10] = ~(_315_ ^ _091_);
  assign _316_ = _315_ & ~(_091_);
  assign _317_ = _088_ & ~(_316_);
  assign tempa_w[11] = ~(_317_ ^ _087_);
  assign _318_ = _132_ & ~(_102_);
  assign _319_ = _098_ & ~(_318_);
  assign tempa_w[12] = _319_ ^ _083_;
  assign _320_ = ~((_319_ | _083_) & _080_);
  assign tempa_w[13] = ~(_320_ ^ _079_);
  assign _321_ = ~_076_;
  assign _322_ = ~(_319_ | _084_);
  assign _323_ = _322_ | _081_;
  assign tempa_w[14] = _323_ ^ _321_;
  assign _324_ = ~_073_;
  assign _325_ = ~((_323_ & _321_) | _324_);
  assign tempa_w[15] = ~(_325_ ^ _072_);
  assign tempa_w[16] = _133_ ^ _066_;
  assign _326_ = ~((_133_ | _066_) & _058_);
  assign tempa_w[17] = _326_ ^ _057_;
  assign _327_ = ~((_133_ | _067_) & _060_);
  assign tempa_w[18] = ~(_327_ ^ _055_);
  assign _328_ = _327_ & ~(_055_);
  assign _329_ = _052_ & ~(_328_);
  assign tempa_w[19] = ~(_329_ ^ _051_);
  assign _330_ = _061_ | _054_;
  assign _331_ = ~(_132_ & _103_);
  assign _332_ = _099_ | ~(_331_);
  assign _333_ = ~((_332_ & _068_) | _330_);
  assign tempa_w[20] = _333_ ^ _047_;
  assign _334_ = ~((_333_ | _047_) & _042_);
  assign tempa_w[21] = _334_ ^ _041_;
  assign _335_ = ~_039_;
  assign _336_ = ~((_333_ | _048_) & _044_);
  assign tempa_w[22] = _336_ ^ _335_;
  assign _337_ = ~_036_;
  assign _338_ = ~((_336_ & _335_) | _337_);
  assign tempa_w[23] = ~(_338_ ^ _035_);
  assign _339_ = ~_030_;
  assign _340_ = ~((_330_ & _049_) | _046_);
  assign _341_ = ~_069_;
  assign _342_ = ~((_133_ | _341_) & _340_);
  assign tempa_w[24] = _342_ ^ _339_;
  assign _343_ = ~((_342_ & _339_) | _024_);
  assign tempa_w[25] = _343_ ^ _023_;
  assign _344_ = ~_021_;
  assign _345_ = ~((_332_ & _069_) | _064_);
  assign _346_ = ~((_345_ | _031_) & _026_);
  assign tempa_w[26] = _346_ ^ _344_;
  assign _347_ = ~((_346_ & _344_) | _018_);
  assign tempa_w[27] = _347_ ^ _017_;
  assign _348_ = ~_028_;
  assign _349_ = ~((_342_ & _032_) | _348_);
  assign tempa_w[28] = _349_ ^ _013_;
  assign _350_ = ~_009_;
  assign _351_ = ~((_349_ | _013_) & _350_);
  assign tempa_w[29] = ~(_351_ ^ _008_);
  assign _352_ = ~_005_;
  assign _353_ = ~_011_;
  assign _354_ = ~_014_;
  assign _355_ = ~((_349_ | _354_) & _353_);
  assign tempa_w[30] = _355_ ^ _352_;
  assign _356_ = ~((_355_ & _352_) | _002_);
  assign tempa_w[31] = _356_ ^ _001_;
  assign tempa_w[0] = aa[0] ^ bb[0];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[27] <= 0;
    else
      tempb_r[27] <= tempb_w[27];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[28] <= 0;
    else
      tempb_r[28] <= tempb_w[28];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[29] <= 0;
    else
      tempb_r[29] <= tempb_w[29];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[30] <= 0;
    else
      tempb_r[30] <= tempb_w[30];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[31] <= 0;
    else
      tempb_r[31] <= tempb_w[31];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[0] <= 0;
    else
      tempa_r[0] <= tempa_w[0];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[1] <= 0;
    else
      tempa_r[1] <= tempa_w[1];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[2] <= 0;
    else
      tempa_r[2] <= tempa_w[2];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[3] <= 0;
    else
      tempa_r[3] <= tempa_w[3];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[4] <= 0;
    else
      tempa_r[4] <= tempa_w[4];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[5] <= 0;
    else
      tempa_r[5] <= tempa_w[5];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[6] <= 0;
    else
      tempa_r[6] <= tempa_w[6];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[7] <= 0;
    else
      tempa_r[7] <= tempa_w[7];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[8] <= 0;
    else
      tempa_r[8] <= tempa_w[8];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[9] <= 0;
    else
      tempa_r[9] <= tempa_w[9];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[10] <= 0;
    else
      tempa_r[10] <= tempa_w[10];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[11] <= 0;
    else
      tempa_r[11] <= tempa_w[11];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[12] <= 0;
    else
      tempa_r[12] <= tempa_w[12];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[13] <= 0;
    else
      tempa_r[13] <= tempa_w[13];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[14] <= 0;
    else
      tempa_r[14] <= tempa_w[14];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[15] <= 0;
    else
      tempa_r[15] <= tempa_w[15];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[16] <= 0;
    else
      tempa_r[16] <= tempa_w[16];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[17] <= 0;
    else
      tempa_r[17] <= tempa_w[17];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[18] <= 0;
    else
      tempa_r[18] <= tempa_w[18];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[19] <= 0;
    else
      tempa_r[19] <= tempa_w[19];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[20] <= 0;
    else
      tempa_r[20] <= tempa_w[20];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[21] <= 0;
    else
      tempa_r[21] <= tempa_w[21];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[22] <= 0;
    else
      tempa_r[22] <= tempa_w[22];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[23] <= 0;
    else
      tempa_r[23] <= tempa_w[23];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[24] <= 0;
    else
      tempa_r[24] <= tempa_w[24];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[25] <= 0;
    else
      tempa_r[25] <= tempa_w[25];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[26] <= 0;
    else
      tempa_r[26] <= tempa_w[26];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[27] <= 0;
    else
      tempa_r[27] <= tempa_w[27];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[28] <= 0;
    else
      tempa_r[28] <= tempa_w[28];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[29] <= 0;
    else
      tempa_r[29] <= tempa_w[29];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[30] <= 0;
    else
      tempa_r[30] <= tempa_w[30];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[31] <= 0;
    else
      tempa_r[31] <= tempa_w[31];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempa_r[32] <= 0;
    else
      tempa_r[32] <= tempa_w[32];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[0] <= 0;
    else
      c_r[0] <= tempa_r[0];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[1] <= 0;
    else
      c_r[1] <= tempa_r[1];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[2] <= 0;
    else
      c_r[2] <= tempa_r[2];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[3] <= 0;
    else
      c_r[3] <= tempa_r[3];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[4] <= 0;
    else
      c_r[4] <= tempa_r[4];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[5] <= 0;
    else
      c_r[5] <= tempa_r[5];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[6] <= 0;
    else
      c_r[6] <= tempa_r[6];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[7] <= 0;
    else
      c_r[7] <= tempa_r[7];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[8] <= 0;
    else
      c_r[8] <= tempa_r[8];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[9] <= 0;
    else
      c_r[9] <= tempa_r[9];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[10] <= 0;
    else
      c_r[10] <= tempa_r[10];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[11] <= 0;
    else
      c_r[11] <= tempa_r[11];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[12] <= 0;
    else
      c_r[12] <= tempa_r[12];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[13] <= 0;
    else
      c_r[13] <= tempa_r[13];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[14] <= 0;
    else
      c_r[14] <= tempa_r[14];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[15] <= 0;
    else
      c_r[15] <= tempa_r[15];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[16] <= 0;
    else
      c_r[16] <= tempa_r[16];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[17] <= 0;
    else
      c_r[17] <= tempa_r[17];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[18] <= 0;
    else
      c_r[18] <= tempa_r[18];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[19] <= 0;
    else
      c_r[19] <= tempa_r[19];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[20] <= 0;
    else
      c_r[20] <= tempa_r[20];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[21] <= 0;
    else
      c_r[21] <= tempa_r[21];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[22] <= 0;
    else
      c_r[22] <= tempa_r[22];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[23] <= 0;
    else
      c_r[23] <= tempa_r[23];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[24] <= 0;
    else
      c_r[24] <= tempa_r[24];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[25] <= 0;
    else
      c_r[25] <= tempa_r[25];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[26] <= 0;
    else
      c_r[26] <= tempa_r[26];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[27] <= 0;
    else
      c_r[27] <= tempa_r[27];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[28] <= 0;
    else
      c_r[28] <= tempa_r[28];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[29] <= 0;
    else
      c_r[29] <= tempa_r[29];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[30] <= 0;
    else
      c_r[30] <= tempa_r[30];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[31] <= 0;
    else
      c_r[31] <= tempa_r[31];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[32] <= 0;
    else
      c_r[32] <= tempb_r[0];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[33] <= 0;
    else
      c_r[33] <= tempb_r[1];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[34] <= 0;
    else
      c_r[34] <= tempb_r[2];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[35] <= 0;
    else
      c_r[35] <= tempb_r[3];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[36] <= 0;
    else
      c_r[36] <= tempb_r[4];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[37] <= 0;
    else
      c_r[37] <= tempb_r[5];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[38] <= 0;
    else
      c_r[38] <= tempb_r[6];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[39] <= 0;
    else
      c_r[39] <= tempb_r[7];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[40] <= 0;
    else
      c_r[40] <= tempb_r[8];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[41] <= 0;
    else
      c_r[41] <= tempb_r[9];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[42] <= 0;
    else
      c_r[42] <= tempb_r[10];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[43] <= 0;
    else
      c_r[43] <= tempb_r[11];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[44] <= 0;
    else
      c_r[44] <= tempb_r[12];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[45] <= 0;
    else
      c_r[45] <= tempb_r[13];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[46] <= 0;
    else
      c_r[46] <= tempb_r[14];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[47] <= 0;
    else
      c_r[47] <= tempb_r[15];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[48] <= 0;
    else
      c_r[48] <= tempb_r[16];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[49] <= 0;
    else
      c_r[49] <= tempb_r[17];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[50] <= 0;
    else
      c_r[50] <= tempb_r[18];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[51] <= 0;
    else
      c_r[51] <= tempb_r[19];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[52] <= 0;
    else
      c_r[52] <= tempb_r[20];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[53] <= 0;
    else
      c_r[53] <= tempb_r[21];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[54] <= 0;
    else
      c_r[54] <= tempb_r[22];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[55] <= 0;
    else
      c_r[55] <= tempb_r[23];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[56] <= 0;
    else
      c_r[56] <= tempb_r[24];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[57] <= 0;
    else
      c_r[57] <= tempb_r[25];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[58] <= 0;
    else
      c_r[58] <= tempb_r[26];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[59] <= 0;
    else
      c_r[59] <= tempb_r[27];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[60] <= 0;
    else
      c_r[60] <= tempb_r[28];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[61] <= 0;
    else
      c_r[61] <= tempb_r[29];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[62] <= 0;
    else
      c_r[62] <= tempb_r[30];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      c_r[63] <= 0;
    else
      c_r[63] <= tempb_r[31];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[0] <= 0;
    else
      tempb_r[0] <= tempb_w[0];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[1] <= 0;
    else
      tempb_r[1] <= tempb_w[1];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[2] <= 0;
    else
      tempb_r[2] <= tempb_w[2];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[3] <= 0;
    else
      tempb_r[3] <= tempb_w[3];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[4] <= 0;
    else
      tempb_r[4] <= tempb_w[4];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[5] <= 0;
    else
      tempb_r[5] <= tempb_w[5];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[6] <= 0;
    else
      tempb_r[6] <= tempb_w[6];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[7] <= 0;
    else
      tempb_r[7] <= tempb_w[7];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[8] <= 0;
    else
      tempb_r[8] <= tempb_w[8];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[9] <= 0;
    else
      tempb_r[9] <= tempb_w[9];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[10] <= 0;
    else
      tempb_r[10] <= tempb_w[10];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[11] <= 0;
    else
      tempb_r[11] <= tempb_w[11];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[12] <= 0;
    else
      tempb_r[12] <= tempb_w[12];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[13] <= 0;
    else
      tempb_r[13] <= tempb_w[13];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[14] <= 0;
    else
      tempb_r[14] <= tempb_w[14];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[15] <= 0;
    else
      tempb_r[15] <= tempb_w[15];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[16] <= 0;
    else
      tempb_r[16] <= tempb_w[16];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[17] <= 0;
    else
      tempb_r[17] <= tempb_w[17];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[18] <= 0;
    else
      tempb_r[18] <= tempb_w[18];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[19] <= 0;
    else
      tempb_r[19] <= tempb_w[19];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[20] <= 0;
    else
      tempb_r[20] <= tempb_w[20];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[21] <= 0;
    else
      tempb_r[21] <= tempb_w[21];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[22] <= 0;
    else
      tempb_r[22] <= tempb_w[22];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[23] <= 0;
    else
      tempb_r[23] <= tempb_w[23];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[24] <= 0;
    else
      tempb_r[24] <= tempb_w[24];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[25] <= 0;
    else
      tempb_r[25] <= tempb_w[25];
  always @(posedge i_clk or negedge i_rst_n)
    if (!i_rst_n)
      tempb_r[26] <= 0;
    else
      tempb_r[26] <= tempb_w[26];
  assign c = c_r;
  assign c_w = { tempb_r, tempa_r[31:0] };
endmodule
